#pragma once

#define ANSI_COLOR_BLACK "\e[0;30m"
#define ANSI_COLOR_RED "\e[0;31m"
#define ANSI_COLOR_GREEN "\e[0;32m"
#define ANSI_COLOR_YELLOW "\e[0;33m"
#define ANSI_COLOR_BLUE "\e[0;34m"
#define ANSI_COLOR_PURPLE "\e[0;35m"
#define ANSI_COLOR_CYAN "\e[0;36m"
#define ANSI_COLOR_WHITE "\e[0;37m"

#define ANSI_BOLD_COLOR_BLACK "\e[1;30m"
#define ANSI_BOLD_COLOR_RED "\e[1;31m"
#define ANSI_BOLD_COLOR_GREEN "\e[1;32m"
#define ANSI_BOLD_COLOR_YELLOW "\e[1;33m"
#define ANSI_BOLD_COLOR_BLUE "\e[1;34m"
#define ANSI_BOLD_COLOR_PURPLE "\e[1;35m"
#define ANSI_BOLD_COLOR_CYAN "\e[1;36m"
#define ANSI_BOLD_COLOR_WHITE "\e[1;37m"

#define ANSI_HI_COLOR_BLACK "\e[0;90m"
#define ANSI_HI_COLOR_RED "\e[0;91m"
#define ANSI_HI_COLOR_GREEN "\e[0;92m"
#define ANSI_HI_COLOR_YELLOW "\e[0;93m"
#define ANSI_HI_COLOR_BLUE "\e[0;94m"
#define ANSI_HI_COLOR_PURPLE "\e[0;95m"
#define ANSI_HI_COLOR_CYAN "\e[0;96m"
#define ANSI_HI_COLOR_WHITE "\e[0;97m"

#define ANSI_RESET "\e[0m"
